[workspace]
members = [
    "expressions",
    "functions",
    "generics",
    "hello-world",
    "macros",
    "options",
    "primitives",
    "results",
    "traits",
    "variable-bindings",
]
resolver = "2"
