[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
account_already_in_use = "AGG9H9P1LfdnPpr1adrnP4BohUtQzih2a6FxWf6LH7R4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
