[features]
seeds = false
[programs.localnet]
duplicate_mutable_accounts_insecure = "Poo5jhFcGjMjYaz2cpmSNVq4ehvjKJhjU7aCZiS2LMP"
duplicate_mutable_accounts_secure = "Po8QNbexAedzyagU3ZupR7pLeaqe4BmJmrNCaJ8xu6h"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/marcinv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
