[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "J9TXPkyYXLw82XsedHXVq8nMsso8copxRtmpz3oWsoMJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
