[package]
name = "trdelnik-tests"
version = "0.1.0"
description = "Created with Trdelnik"
edition = "2021"

[dev-dependencies]
fehler = "1.0.0"
rstest = "0.12.0"
trdelnik-client = "0.1.6"
borsh = "0.9.3"

[dev-dependencies.program_client]
path = "../.program_client"

[dev-dependencies.type-cosplay-insecure]
path = "../programs/insecure"

[dev-dependencies.type-cosplay-secure]
path = "../programs/secure"
