[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
account_did_not_deserialize = "9GxG8C77oRp9Xej1dr8oKzFU6F7oYMeVbkFT91SrbxDa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
