[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
no_prior_credit = "Gybnrf2yQZiaAmBQ33dtFkvpWBDWeHaxkuiUoqsFg6Mo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
