[package]
name = "trdelnik-tests"
version = "0.1.0"
description = "Created with Trdelnik"
edition = "2021"

[dev-dependencies]
fehler = "1.0.0"
rstest = "0.12.0"
trdelnik-client = "0.1.6"

[dev-dependencies.program_client]
path = "../.program_client"

[dev-dependencies.auction]
path = "../programs/auction"
