[features]
resolution = true
skip-lint = false

[programs.localnet]
bank = "6X5dFH4CLG7YNdrTu7X2s4LmFnKpsPxN1X19L9w3C5eJ"

[programs.devnet]
bank = "6X5dFH4CLG7YNdrTu7X2s4LmFnKpsPxN1X19L9w3C5eJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
